
[env]
TERM = "xterm-256color"

[font]
size = 15.0

[window.padding]
x = 10
y = 10

[general]
live_config_reload = true

import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
